services:  
  app:
    image: hello-front-dev
    build:
      context: ./todo-frontend
    volumes:
      - ./todo-frontend/:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: hello-front-dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo
    
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

  server:
    image: hello-back-dev
    build:
      context: ./todo-backend/
    volumes:
      - ./todo-backend/:/usr/src/app   
    environment: 
        - REDIS_URL=redis://redis:6379
        - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: hello-back-dev
    depends_on:
      - mongo
      - redis
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app    


volumes:
  mongo_data:
  redis_data:
